ALTER SERVER ROLE [sysadmin] ADD MEMBER [LAPTOP-VR0BE1TH\juned];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

