name: build-pipeline
on:
    pull_request:
        branches:
            - prod
jobs:
    codelint:
        name: "lint code"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
      
        - name: Lint code
          uses: github/super-linter@v5
          env:
           DEFAULT_BRANCH: prod
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
           DISABLE_ERRORS: true
    build:
        name: "build code"
        needs: [codelint]
        runs-on: self-hosted
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: add msbuild to path
              uses: microsoft/setup-msbuild@v1.3.1
            - name: Build now
              run: |
                msbuild -p:Configuration=Release
            # Publish artifact
            - uses: actions/upload-artifact@v3.1.2
              with:
                  name: MSSQLCICDTEST
                  path: ${{ github.workspace }}\MSSQLCICD\bin\Release\
    deploytestenv:
        name: deploy on test enviorment
        needs: [build]
        environment: prodenv
        runs-on: self-hosted
        steps:
            - name: download artifact
              uses: actions/download-artifact@v3.0.2
              with:
                name: MSSQLCICDTEST
            - name : publish package to test database on local server
              run: |
                sqlpackage.exe /a:Publish /sf:"MSSQLCICD.dacpac" /tcs:"${{ secrets.SQL_CONNECTION_STRING }}"
            
